### ISSUE TITLE
Game crash when player joins

### ISSUE THREAD

**Issue by GoldenMine0502** [Sparks-and-Rotation/woodencog#14]
https://github.com/AllTheMods/Gravitas2/issues/157

**Comment by GoldenMine0502** [comment]
success all of stack or not

**Comment by chauve-dev** [comment]
Hey i didn't checked the log i'll do it later but i may know where this come from, i'll fix this when i start working on the mod again

**Comment by GoldenMine0502** [comment]
thanks and i made mistake closing this issue
